language: swift
osx_image: xcode10
script:
- xcodebuild clean -project NeoSwift.xcodeproj -scheme NeoSwift -destination "platform=iOS Simulator,name=iPhone XS Max,OS=12.0" -configuration Releas -enableCodeCoverage YES build test
- bash <(curl -s https://codecov.io/bash) -cF ios