// Objective-C API for talking to golang.org/x/mobile/example/keygen Go package.
//   gobind -lang=objc golang.org/x/mobile/example/keygen
//
// File is generated by gobind. Do not edit.

#ifndef __GoKeygen_H__
#define __GoKeygen_H__

@import Foundation;
#include "GoUniverse.objc.h"


@class GoKeygenWallet;

@interface GoKeygenWallet : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSData*)publicKey;
- (void)setPublicKey:(NSData*)v;
- (NSData*)privateKey;
- (void)setPrivateKey:(NSData*)v;
- (NSString*)address;
- (void)setAddress:(NSString*)v;
- (NSString*)wif;
- (void)setWIF:(NSString*)v;
@end

FOUNDATION_EXPORT GoKeygenWallet* GoKeygenGenerateFromWIF(NSString* wif, NSError** error);

FOUNDATION_EXPORT GoKeygenWallet* GoKeygenGeneratePublicKeyFromPrivateKey(NSString* privateKey, NSError** error);

#endif
