
// Objective-C API for talking to the following Go packages
//
//	golang.org/x/mobile/example/keygen
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Keygen_H__
#define __Keygen_H__

#include "GoKeygen.objc.h"
#include "GoUniverse.objc.h"

#endif
