
// Objective-C API for talking to the following Go packages
//
//	golang.org/x/mobile/example/neo-wallet-address-go
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Neowallet_H__
#define __Neowallet_H__

#include "GoNeowallet.objc.h"
#include "GoUniverse.objc.h"

#endif
