
// Objective-C API for talking to the following Go packages
//
//	github.com/o3labs/neo-wallet-address-go
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Neowallet_FRAMEWORK_H__
#define __Neowallet_FRAMEWORK_H__

#include "Neowallet.objc.h"
#include "Universe.objc.h"

#endif
