
// Objective-C API for talking to the following Go packages
//
//	github.com/o3labs/neo-utils/neoutils
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Neoutils_FRAMEWORK_H__
#define __Neoutils_FRAMEWORK_H__

#include "Neoutils.objc.h"
#include "universe.objc.h"

#endif
